### ISSUE TITLE
Cusotm Events

### ISSUE THREAD

**Issue by j-garin** [khacpv/Calendar-Day-View#4]
I've created a new public class (CalendarEvent) that implements IEvent, but am unable to call 

```
List<CalendarEvent> events = new ArrayList<>();
dayView.setEvents(events);
```
it doesn't recognize my list as an appoicable argument.

**Comment by khacpv** [comment]
I don't know why too, sorry. Please make sure that `CalendarEvent` implement `IEvent`, or you need to clean/rebuild your code.

**Comment by j-garin** [comment]
@khacpv done all that, doesn't work. 

Checked your source code. It seems that you need to replace List<IEvent> with List<? extends IEvent> in your code and it will work.

**Comment by khacpv** [comment]
you're right!, Thanks for your proposal 🙌
