### ISSUE TITLE
Event color doesn't change

### ISSUE THREAD

**Issue by Y2JChamp** [khacpv/Calendar-Day-View#6]
Hello, i'm adding three events to the dayView, giving them different colors, but it shows the same color for all the events.
I'm doing like this:

events.add(createEvent(1, entranceTime, jobTime1, R.color.entranceOrExitColor, "Entrata"));
events.add(createEvent(2, jobTime1, jobTime2, R.color.jobColor, "Al lavoro"));
events.add(createEvent(3, jobTime2, exitTime, R.color.entranceOrExitColor, "Uscita"));
dayView.setEvents(events);

private MyEvent createEvent(long id,Date timbTime1, Date timbTime2, int color, String eventType){
        Calendar timeStart = Calendar.getInstance();
        timeStart.set(Calendar.HOUR_OF_DAY, parseInt((DateFormat.format("HH", timbTime1).toString())));
        timeStart.set(Calendar.MINUTE, parseInt((DateFormat.format("mm", timbTime1).toString())));
        Calendar timeEnd = Calendar.getInstance();
        timeEnd.set(Calendar.HOUR_OF_DAY, parseInt((DateFormat.format("HH", timbTime2).toString())));
        timeEnd.set(Calendar.MINUTE, parseInt((DateFormat.format("mm", timbTime2).toString())));
        return new MyEvent(id, timeStart, timeEnd, eventType, color);
    }

**Comment by khacpv** [comment]
color value should be `color format`, not by resource int.
You should use 
`int eventColor = ContextCompat.getColor(context, R.color.eventColor1);`
instead of 
`R.color.eventColor1`
